# Generated by Django 4.1.3 on 2022-12-02 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produto',
            table='produtos',
        ),
    ]
